apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: desafio8
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
